//
// Milkyway Hierarchical Verilog Dump:
// Generated on 03/13/2017 at 07:23:39
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :fsm
// Cell Name    :fsm
// Hierarchy delimiter:'/'
// Write Command : write_verilog ./output_pnr/fsm_icc.v -pg -no_physical_only_cells
//


module fsm (Haddr , Hwdata , Prdata , Hrdata , Htrans , Pwdata , 
    Paddr , Hwrite , Hrstn , Hclk , Hresp , test_so , Pwrite , Pselx , 
    Penable , Hready_out , test_se , test_si , Hsel_APB );
input  [31:0] Haddr ;
input  [31:0] Hwdata ;
input  [31:0] Prdata ;
output [31:0] Hrdata ;
input  [1:0] Htrans ;
output [31:0] Pwdata ;
output [31:0] Paddr ;
input  Hwrite ;
input  Hrstn ;
input  Hclk ;
output [1:0] Hresp ;
output test_so ;
output Pwrite ;
output Pselx ;
output Penable ;
output Hready_out ;
input  test_se ;
input  test_si ;
input  Hsel_APB ;

supply0 VSS ;

supply1 VDD ;
wire [2:0] current_state ;
wire [2:0] next_state ;
wire SPARE_PREFIX_NAME_0_A1 ;
assign SPARE_PREFIX_NAME_0_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_A1_A2 ;
assign SPARE_PREFIX_NAME_0_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_1_A1 ;
assign SPARE_PREFIX_NAME_1_A1 = 1'b0;
wire SPARE_PREFIX_NAME_1_A1_A2 ;
assign SPARE_PREFIX_NAME_1_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_2_A1 ;
assign SPARE_PREFIX_NAME_2_A1 = 1'b0;
wire SPARE_PREFIX_NAME_2_A1_A2 ;
assign SPARE_PREFIX_NAME_2_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_3_A1 ;
assign SPARE_PREFIX_NAME_3_A1 = 1'b0;
wire SPARE_PREFIX_NAME_3_A1_A2 ;
assign SPARE_PREFIX_NAME_3_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_4_A1 ;
assign SPARE_PREFIX_NAME_4_A1 = 1'b0;
wire SPARE_PREFIX_NAME_4_A1_A2 ;
assign SPARE_PREFIX_NAME_4_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_5_A1 ;
assign SPARE_PREFIX_NAME_5_A1 = 1'b0;
wire SPARE_PREFIX_NAME_5_A1_A2 ;
assign SPARE_PREFIX_NAME_5_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_6_A1 ;
assign SPARE_PREFIX_NAME_6_A1 = 1'b0;
wire SPARE_PREFIX_NAME_6_A1_A2 ;
assign SPARE_PREFIX_NAME_6_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_7_A1 ;
assign SPARE_PREFIX_NAME_7_A1 = 1'b0;
wire SPARE_PREFIX_NAME_7_A1_A2 ;
assign SPARE_PREFIX_NAME_7_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_8_A1 ;
assign SPARE_PREFIX_NAME_8_A1 = 1'b0;
wire SPARE_PREFIX_NAME_8_A1_A2 ;
assign SPARE_PREFIX_NAME_8_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_9_A1 ;
assign SPARE_PREFIX_NAME_9_A1 = 1'b0;
wire SPARE_PREFIX_NAME_9_A1_A2 ;
assign SPARE_PREFIX_NAME_9_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_10_A1 ;
assign SPARE_PREFIX_NAME_10_A1 = 1'b0;
wire SPARE_PREFIX_NAME_10_A1_A2 ;
assign SPARE_PREFIX_NAME_10_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_11_A1 ;
assign SPARE_PREFIX_NAME_11_A1 = 1'b0;
wire SPARE_PREFIX_NAME_11_A1_A2 ;
assign SPARE_PREFIX_NAME_11_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_12_A1 ;
assign SPARE_PREFIX_NAME_12_A1 = 1'b0;
wire SPARE_PREFIX_NAME_12_A1_A2 ;
assign SPARE_PREFIX_NAME_12_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_13_A1 ;
assign SPARE_PREFIX_NAME_13_A1 = 1'b0;
wire SPARE_PREFIX_NAME_13_A1_A2 ;
assign SPARE_PREFIX_NAME_13_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_14_A1 ;
assign SPARE_PREFIX_NAME_14_A1 = 1'b0;
wire SPARE_PREFIX_NAME_14_A1_A2 ;
assign SPARE_PREFIX_NAME_14_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_15_A1 ;
assign SPARE_PREFIX_NAME_15_A1 = 1'b0;
wire SPARE_PREFIX_NAME_15_A1_A2 ;
assign SPARE_PREFIX_NAME_15_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_16_A1 ;
assign SPARE_PREFIX_NAME_16_A1 = 1'b0;
wire SPARE_PREFIX_NAME_16_A1_A2 ;
assign SPARE_PREFIX_NAME_16_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_17_A1 ;
assign SPARE_PREFIX_NAME_17_A1 = 1'b0;
wire SPARE_PREFIX_NAME_17_A1_A2 ;
assign SPARE_PREFIX_NAME_17_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_18_A1 ;
assign SPARE_PREFIX_NAME_18_A1 = 1'b0;
wire SPARE_PREFIX_NAME_18_A1_A2 ;
assign SPARE_PREFIX_NAME_18_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_19_A1 ;
assign SPARE_PREFIX_NAME_19_A1 = 1'b0;
wire SPARE_PREFIX_NAME_19_A1_A2 ;
assign SPARE_PREFIX_NAME_19_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_0_A1 ;
assign SPARE_PREFIX_NAME_0_0_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_0_A1_A2 ;
assign SPARE_PREFIX_NAME_0_0_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_1_A1 ;
assign SPARE_PREFIX_NAME_0_1_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_1_A1_A2 ;
assign SPARE_PREFIX_NAME_0_1_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_2_A1 ;
assign SPARE_PREFIX_NAME_0_2_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_2_A1_A2 ;
assign SPARE_PREFIX_NAME_0_2_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_3_A1 ;
assign SPARE_PREFIX_NAME_0_3_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_3_A1_A2 ;
assign SPARE_PREFIX_NAME_0_3_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_4_A1 ;
assign SPARE_PREFIX_NAME_0_4_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_4_A1_A2 ;
assign SPARE_PREFIX_NAME_0_4_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_5_A1 ;
assign SPARE_PREFIX_NAME_0_5_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_5_A1_A2 ;
assign SPARE_PREFIX_NAME_0_5_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_6_A1 ;
assign SPARE_PREFIX_NAME_0_6_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_6_A1_A2 ;
assign SPARE_PREFIX_NAME_0_6_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_7_A1 ;
assign SPARE_PREFIX_NAME_0_7_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_7_A1_A2 ;
assign SPARE_PREFIX_NAME_0_7_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_8_A1 ;
assign SPARE_PREFIX_NAME_0_8_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_8_A1_A2 ;
assign SPARE_PREFIX_NAME_0_8_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_9_A1 ;
assign SPARE_PREFIX_NAME_0_9_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_9_A1_A2 ;
assign SPARE_PREFIX_NAME_0_9_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_10_A1 ;
assign SPARE_PREFIX_NAME_0_10_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_10_A1_A2 ;
assign SPARE_PREFIX_NAME_0_10_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_11_A1 ;
assign SPARE_PREFIX_NAME_0_11_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_11_A1_A2 ;
assign SPARE_PREFIX_NAME_0_11_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_12_A1 ;
assign SPARE_PREFIX_NAME_0_12_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_12_A1_A2 ;
assign SPARE_PREFIX_NAME_0_12_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_13_A1 ;
assign SPARE_PREFIX_NAME_0_13_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_13_A1_A2 ;
assign SPARE_PREFIX_NAME_0_13_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_14_A1 ;
assign SPARE_PREFIX_NAME_0_14_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_14_A1_A2 ;
assign SPARE_PREFIX_NAME_0_14_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_15_A1 ;
assign SPARE_PREFIX_NAME_0_15_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_15_A1_A2 ;
assign SPARE_PREFIX_NAME_0_15_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_16_A1 ;
assign SPARE_PREFIX_NAME_0_16_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_16_A1_A2 ;
assign SPARE_PREFIX_NAME_0_16_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_17_A1 ;
assign SPARE_PREFIX_NAME_0_17_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_17_A1_A2 ;
assign SPARE_PREFIX_NAME_0_17_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_18_A1 ;
assign SPARE_PREFIX_NAME_0_18_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_18_A1_A2 ;
assign SPARE_PREFIX_NAME_0_18_A1_A2 = 1'b0;
wire SPARE_PREFIX_NAME_0_19_A1 ;
assign SPARE_PREFIX_NAME_0_19_A1 = 1'b0;
wire SPARE_PREFIX_NAME_0_19_A1_A2 ;
assign SPARE_PREFIX_NAME_0_19_A1_A2 = 1'b0;

assign Hresp[0] = Hresp[1] ;
INV_X1 U34 (.A ( n14 ) , .ZN ( n101 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U33 (.A ( n14 ) , .ZN ( n100 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U32 (.A ( n26 ) , .ZN ( n99 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U31 (.A ( n26 ) , .ZN ( n98 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U30 (.A ( n26 ) , .ZN ( n97 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U28 (.A ( n79 ) , .ZN ( n96 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U27 (.A ( n79 ) , .ZN ( n95 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U26 (.A ( n85 ) , .ZN ( n94 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U25 (.A ( n79 ) , .ZN ( n93 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U24 (.A ( n13 ) , .ZN ( n92 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U23 (.A ( n13 ) , .ZN ( n91 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U22 (.A ( n12 ) , .ZN ( n90 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U17 (.A ( n12 ) , .ZN ( n89 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U16 (.A ( n86 ) , .ZN ( n88 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U12 (.A ( n86 ) , .ZN ( n87 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U10 (.A ( current_state[1] ) , .ZN ( n86 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
INV_X1 U1 (.A ( n25 ) , .ZN ( n85 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U4 (.A ( n12 ) , .ZN ( Pwrite ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U5 (.A ( n13 ) , .ZN ( n82 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U3 (.A ( n79 ) , .ZN ( n80 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U7 (.A ( n26 ) , .ZN ( n83 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U8 (.A ( n14 ) , .ZN ( n84 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U2 (.A ( n25 ) , .ZN ( n79 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U29 (.A ( n56 ) , .ZN ( n71 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U21 (.A1 ( n57 ) , .A2 ( n88 ) , .ZN ( n63 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U20 (.A1 ( n57 ) , .A2 ( current_state[1] ) , .ZN ( n62 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U19 (.A1 ( n9 ) , .A2 ( n87 ) , .ZN ( n61 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U18 (.A1 ( n9 ) , .A2 ( n87 ) , .ZN ( n60 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U15 (.A1 ( n3 ) , .A2 ( n6 ) , .ZN ( n57 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
NAND2_X1 U13 (.A1 ( current_state[0] ) , .A2 ( n86 ) , .ZN ( n56 ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U11 (.A ( n56 ) , .ZN ( n54 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X1 U14 (.A1 ( current_state[0] ) , .A2 ( n86 ) , .ZN ( n26 ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U9 (.A1 ( current_state[2] ) , .A2 ( n5 ) , .ZN ( n25 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U6 (.A1 ( n57 ) , .A2 ( n88 ) , .ZN ( n22 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U156 (.A1 ( Hwdata[5] ) , .A2 ( n89 ) , .ZN ( Pwdata[5] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U157 (.A1 ( Hwdata[6] ) , .A2 ( n93 ) , .ZN ( Pwdata[6] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U158 (.A1 ( Hwdata[7] ) , .A2 ( n93 ) , .ZN ( Pwdata[7] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U159 (.A1 ( Hwdata[8] ) , .A2 ( Pwrite ) , .ZN ( Pwdata[8] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U160 (.A1 ( Hwdata[9] ) , .A2 ( n89 ) , .ZN ( Pwdata[9] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U161 (.A1 ( Hwdata[10] ) , .A2 ( n80 ) , .ZN ( Pwdata[10] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U162 (.A1 ( Hwdata[11] ) , .A2 ( n93 ) , .ZN ( Pwdata[11] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U163 (.A1 ( Hwdata[12] ) , .A2 ( Pwrite ) , .ZN ( Pwdata[12] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U164 (.A1 ( Hwdata[13] ) , .A2 ( n96 ) , .ZN ( Pwdata[13] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U165 (.A1 ( Hwdata[14] ) , .A2 ( n96 ) , .ZN ( Pwdata[14] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U166 (.A1 ( Hwdata[15] ) , .A2 ( n96 ) , .ZN ( Pwdata[15] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U167 (.A1 ( Hwdata[16] ) , .A2 ( n93 ) , .ZN ( Pwdata[16] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U168 (.A1 ( Hwdata[17] ) , .A2 ( n96 ) , .ZN ( Pwdata[17] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U169 (.A1 ( Hwdata[18] ) , .A2 ( Pwrite ) , .ZN ( Pwdata[18] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U170 (.A1 ( Hwdata[19] ) , .A2 ( n95 ) , .ZN ( Pwdata[19] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U171 (.A1 ( Hwdata[20] ) , .A2 ( n95 ) , .ZN ( Pwdata[20] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U172 (.A1 ( Hwdata[21] ) , .A2 ( n95 ) , .ZN ( Pwdata[21] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U173 (.A1 ( Hwdata[22] ) , .A2 ( n90 ) , .ZN ( Pwdata[22] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U174 (.A1 ( Hwdata[23] ) , .A2 ( n94 ) , .ZN ( Pwdata[23] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U175 (.A1 ( Hwdata[24] ) , .A2 ( n90 ) , .ZN ( Pwdata[24] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U176 (.A1 ( Hwdata[25] ) , .A2 ( n90 ) , .ZN ( Pwdata[25] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U177 (.A1 ( Hwdata[26] ) , .A2 ( n90 ) , .ZN ( Pwdata[26] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U178 (.A1 ( Hwdata[27] ) , .A2 ( n94 ) , .ZN ( Pwdata[27] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U179 (.A1 ( Hwdata[28] ) , .A2 ( n94 ) , .ZN ( Pwdata[28] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U180 (.A1 ( Hwdata[29] ) , .A2 ( n94 ) , .ZN ( Pwdata[29] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U181 (.A1 ( Hwdata[30] ) , .A2 ( n95 ) , .ZN ( Pwdata[30] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U182 (.A1 ( Hwdata[31] ) , .A2 ( Pwrite ) , .ZN ( Pwdata[31] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U183 (.A1 ( Prdata[0] ) , .A2 ( n62 ) , .ZN ( Hrdata[0] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U184 (.A1 ( Prdata[1] ) , .A2 ( n62 ) , .ZN ( Hrdata[1] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U185 (.A1 ( Prdata[2] ) , .A2 ( n84 ) , .ZN ( Hrdata[2] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U186 (.A1 ( Prdata[3] ) , .A2 ( n61 ) , .ZN ( Hrdata[3] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U187 (.A1 ( Prdata[4] ) , .A2 ( n61 ) , .ZN ( Hrdata[4] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U188 (.A1 ( Prdata[5] ) , .A2 ( n101 ) , .ZN ( Hrdata[5] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U189 (.A1 ( Prdata[6] ) , .A2 ( n61 ) , .ZN ( Hrdata[6] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U190 (.A1 ( Prdata[7] ) , .A2 ( n101 ) , .ZN ( Hrdata[7] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U191 (.A1 ( Prdata[8] ) , .A2 ( n101 ) , .ZN ( Hrdata[8] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U192 (.A1 ( Prdata[9] ) , .A2 ( n101 ) , .ZN ( Hrdata[9] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U193 (.A1 ( Prdata[10] ) , .A2 ( n62 ) , .ZN ( Hrdata[10] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U194 (.A1 ( Prdata[11] ) , .A2 ( n62 ) , .ZN ( Hrdata[11] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U195 (.A1 ( Prdata[12] ) , .A2 ( n63 ) , .ZN ( Hrdata[12] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U196 (.A1 ( Prdata[13] ) , .A2 ( n84 ) , .ZN ( Hrdata[13] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U197 (.A1 ( Prdata[14] ) , .A2 ( n100 ) , .ZN ( Hrdata[14] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U198 (.A1 ( Prdata[15] ) , .A2 ( n100 ) , .ZN ( Hrdata[15] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U199 (.A1 ( Prdata[16] ) , .A2 ( n84 ) , .ZN ( Hrdata[16] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U200 (.A1 ( Prdata[17] ) , .A2 ( n63 ) , .ZN ( Hrdata[17] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U201 (.A1 ( Prdata[18] ) , .A2 ( n63 ) , .ZN ( Hrdata[18] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U202 (.A1 ( Prdata[19] ) , .A2 ( n63 ) , .ZN ( Hrdata[19] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U203 (.A1 ( Prdata[20] ) , .A2 ( n100 ) , .ZN ( Hrdata[20] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U204 (.A1 ( Prdata[21] ) , .A2 ( n84 ) , .ZN ( Hrdata[21] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U205 (.A1 ( Prdata[22] ) , .A2 ( n60 ) , .ZN ( Hrdata[22] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U206 (.A1 ( Prdata[23] ) , .A2 ( n22 ) , .ZN ( Hrdata[23] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U207 (.A1 ( Prdata[24] ) , .A2 ( n60 ) , .ZN ( Hrdata[24] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U208 (.A1 ( Prdata[25] ) , .A2 ( n60 ) , .ZN ( Hrdata[25] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U209 (.A1 ( Prdata[26] ) , .A2 ( n22 ) , .ZN ( Hrdata[26] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U210 (.A1 ( Prdata[27] ) , .A2 ( n60 ) , .ZN ( Hrdata[27] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U211 (.A1 ( Prdata[28] ) , .A2 ( n22 ) , .ZN ( Hrdata[28] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U212 (.A1 ( Prdata[29] ) , .A2 ( n22 ) , .ZN ( Hrdata[29] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U213 (.A1 ( Prdata[30] ) , .A2 ( n100 ) , .ZN ( Hrdata[30] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U214 (.A1 ( Prdata[31] ) , .A2 ( n61 ) , .ZN ( Hrdata[31] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U215 (.A1 ( Haddr[0] ) , .A2 ( n92 ) , .ZN ( Paddr[0] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
OAI22_X1 U216 (.A1 ( n92 ) , .A2 ( n11 ) , .B1 ( n6 ) , .B2 ( n15 ) 
    , .ZN ( next_state[0] ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OAI21_X1 U217 (.A ( n8 ) , .B1 ( n88 ) , .B2 ( n15 ) , .ZN ( next_state[2] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OAI21_X1 U218 (.A ( n10 ) , .B1 ( n87 ) , .B2 ( n9 ) , .ZN ( next_state[1] ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
DFFR_X1 current_state_reg_0_ (.D ( next_state[0] ) , .RN ( Hrstn ) 
    , .CK ( Hclk ) , .Q ( current_state[0] ) , .QN ( n6 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
DFFR_X1 current_state_reg_1_ (.D ( next_state[1] ) , .RN ( Hrstn ) 
    , .CK ( Hclk ) , .Q ( current_state[1] ) , .QN ( n5 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
DFFR_X1 current_state_reg_2_ (.D ( next_state[2] ) , .RN ( Hrstn ) 
    , .CK ( Hclk ) , .Q ( current_state[2] ) , .QN ( n3 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
INV_X1 U108 (.A ( n11 ) , .ZN ( n7 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND3_X1 U109 (.A1 ( current_state[0] ) , .A2 ( n15 ) , .A3 ( n88 ) , .ZN ( n8 ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND3_X1 U110 (.A1 ( n7 ) , .A2 ( n6 ) , .A3 ( Hwrite ) , .ZN ( n10 ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X1 U111 (.A1 ( Htrans[1] ) , .A2 ( Hsel_APB ) , .ZN ( n11 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
NAND2_X1 U112 (.A1 ( n12 ) , .A2 ( n13 ) , .ZN ( Pselx ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
NAND2_X1 U113 (.A1 ( current_state[2] ) , .A2 ( n5 ) , .ZN ( n12 ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X1 U114 (.A1 ( current_state[0] ) , .A2 ( n5 ) , .ZN ( n13 ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X1 U115 (.A1 ( n9 ) , .A2 ( current_state[1] ) , .ZN ( n14 ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
INV_X1 U116 (.A ( current_state[2] ) , .ZN ( n15 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
OR2_X1 U117 (.A1 ( n57 ) , .A2 ( Penable ) , .ZN ( Hready_out ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
OAI21_X1 U118 (.A ( n14 ) , .B1 ( n5 ) , .B2 ( n15 ) , .ZN ( Penable ) 
    , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
AND2_X1 U119 (.A1 ( n3 ) , .A2 ( n6 ) , .ZN ( n9 ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U120 (.A1 ( Haddr[7] ) , .A2 ( n82 ) , .ZN ( Paddr[7] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U121 (.A1 ( Haddr[8] ) , .A2 ( n71 ) , .ZN ( Paddr[8] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U122 (.A1 ( Haddr[9] ) , .A2 ( n99 ) , .ZN ( Paddr[9] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U123 (.A1 ( Haddr[1] ) , .A2 ( n97 ) , .ZN ( Paddr[1] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U124 (.A1 ( Haddr[2] ) , .A2 ( n83 ) , .ZN ( Paddr[2] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U125 (.A1 ( Haddr[3] ) , .A2 ( n71 ) , .ZN ( Paddr[3] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U126 (.A1 ( Haddr[4] ) , .A2 ( n98 ) , .ZN ( Paddr[4] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U127 (.A1 ( Haddr[5] ) , .A2 ( n98 ) , .ZN ( Paddr[5] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U128 (.A1 ( Haddr[6] ) , .A2 ( n99 ) , .ZN ( Paddr[6] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U129 (.A1 ( Haddr[10] ) , .A2 ( n71 ) , .ZN ( Paddr[10] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U130 (.A1 ( Haddr[11] ) , .A2 ( n54 ) , .ZN ( Paddr[11] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U131 (.A1 ( Haddr[12] ) , .A2 ( n82 ) , .ZN ( Paddr[12] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U132 (.A1 ( Haddr[13] ) , .A2 ( n91 ) , .ZN ( Paddr[13] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U133 (.A1 ( Haddr[14] ) , .A2 ( n98 ) , .ZN ( Paddr[14] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U134 (.A1 ( Haddr[15] ) , .A2 ( n99 ) , .ZN ( Paddr[15] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U135 (.A1 ( Haddr[16] ) , .A2 ( n99 ) , .ZN ( Paddr[16] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U136 (.A1 ( Haddr[17] ) , .A2 ( n98 ) , .ZN ( Paddr[17] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U137 (.A1 ( Haddr[18] ) , .A2 ( n82 ) , .ZN ( Paddr[18] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U138 (.A1 ( Haddr[19] ) , .A2 ( n91 ) , .ZN ( Paddr[19] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U139 (.A1 ( Haddr[20] ) , .A2 ( n91 ) , .ZN ( Paddr[20] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U140 (.A1 ( Haddr[21] ) , .A2 ( n83 ) , .ZN ( Paddr[21] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U141 (.A1 ( Haddr[22] ) , .A2 ( n83 ) , .ZN ( Paddr[22] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U142 (.A1 ( Haddr[23] ) , .A2 ( n97 ) , .ZN ( Paddr[23] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U143 (.A1 ( Haddr[24] ) , .A2 ( n97 ) , .ZN ( Paddr[24] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U144 (.A1 ( Haddr[25] ) , .A2 ( n83 ) , .ZN ( Paddr[25] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U145 (.A1 ( Haddr[26] ) , .A2 ( n71 ) , .ZN ( Paddr[26] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U146 (.A1 ( Haddr[27] ) , .A2 ( n82 ) , .ZN ( Paddr[27] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U147 (.A1 ( Haddr[28] ) , .A2 ( n97 ) , .ZN ( Paddr[28] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U148 (.A1 ( Haddr[29] ) , .A2 ( n92 ) , .ZN ( Paddr[29] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U149 (.A1 ( Haddr[30] ) , .A2 ( n91 ) , .ZN ( Paddr[30] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U150 (.A1 ( Haddr[31] ) , .A2 ( n92 ) , .ZN ( Paddr[31] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U151 (.A1 ( Hwdata[0] ) , .A2 ( n80 ) , .ZN ( Pwdata[0] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U152 (.A1 ( Hwdata[1] ) , .A2 ( n80 ) , .ZN ( Pwdata[1] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U153 (.A1 ( Hwdata[2] ) , .A2 ( n80 ) , .ZN ( Pwdata[2] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U154 (.A1 ( Hwdata[3] ) , .A2 ( n89 ) , .ZN ( Pwdata[3] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
AND2_X1 U155 (.A1 ( Hwdata[4] ) , .A2 ( n89 ) , .ZN ( Pwdata[4] ) , .VDD ( VDD ) 
    , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_0 (.A1 ( SPARE_PREFIX_NAME_0_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_1 (.A1 ( SPARE_PREFIX_NAME_1_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_1_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_2 (.A1 ( SPARE_PREFIX_NAME_2_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_2_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_3 (.A1 ( SPARE_PREFIX_NAME_3_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_3_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_4 (.A1 ( SPARE_PREFIX_NAME_4_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_4_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_5 (.A1 ( SPARE_PREFIX_NAME_5_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_5_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_6 (.A1 ( SPARE_PREFIX_NAME_6_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_6_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_7 (.A1 ( SPARE_PREFIX_NAME_7_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_7_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_8 (.A1 ( SPARE_PREFIX_NAME_8_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_8_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_9 (.A1 ( SPARE_PREFIX_NAME_9_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_9_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_10 (.A1 ( SPARE_PREFIX_NAME_10_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_10_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_11 (.A1 ( SPARE_PREFIX_NAME_11_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_11_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_12 (.A1 ( SPARE_PREFIX_NAME_12_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_12_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_13 (.A1 ( SPARE_PREFIX_NAME_13_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_13_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_14 (.A1 ( SPARE_PREFIX_NAME_14_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_14_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_15 (.A1 ( SPARE_PREFIX_NAME_15_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_15_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_16 (.A1 ( SPARE_PREFIX_NAME_16_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_16_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_17 (.A1 ( SPARE_PREFIX_NAME_17_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_17_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_18 (.A1 ( SPARE_PREFIX_NAME_18_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_18_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
OR2_X4 SPARE_PREFIX_NAME_19 (.A1 ( SPARE_PREFIX_NAME_19_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_19_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_0 (.A1 ( SPARE_PREFIX_NAME_0_0_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_0_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_1 (.A1 ( SPARE_PREFIX_NAME_0_1_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_1_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_2 (.A1 ( SPARE_PREFIX_NAME_0_2_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_2_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_3 (.A1 ( SPARE_PREFIX_NAME_0_3_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_3_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_4 (.A1 ( SPARE_PREFIX_NAME_0_4_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_4_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_5 (.A1 ( SPARE_PREFIX_NAME_0_5_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_5_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_6 (.A1 ( SPARE_PREFIX_NAME_0_6_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_6_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_7 (.A1 ( SPARE_PREFIX_NAME_0_7_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_7_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_8 (.A1 ( SPARE_PREFIX_NAME_0_8_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_8_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_9 (.A1 ( SPARE_PREFIX_NAME_0_9_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_9_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_10 (.A1 ( SPARE_PREFIX_NAME_0_10_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_10_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_11 (.A1 ( SPARE_PREFIX_NAME_0_11_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_11_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_12 (.A1 ( SPARE_PREFIX_NAME_0_12_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_12_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_13 (.A1 ( SPARE_PREFIX_NAME_0_13_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_13_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_14 (.A1 ( SPARE_PREFIX_NAME_0_14_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_14_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_15 (.A1 ( SPARE_PREFIX_NAME_0_15_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_15_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_16 (.A1 ( SPARE_PREFIX_NAME_0_16_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_16_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_17 (.A1 ( SPARE_PREFIX_NAME_0_17_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_17_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_18 (.A1 ( SPARE_PREFIX_NAME_0_18_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_18_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
NAND2_X4 SPARE_PREFIX_NAME_0_19 (.A1 ( SPARE_PREFIX_NAME_0_19_A1 ) 
    , .A2 ( SPARE_PREFIX_NAME_0_19_A1_A2 ) , .VDD ( VDD ) , .VSS ( Hresp[1] ) ) ;
assign Hresp[1] = VSS ;
endmodule


