set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction horizontal  -start_at 1.8000 -nets VDD -layer 23 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 127.6000 -nets VDD -layer 23 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 128.1400 -nets VDD -layer 25 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.8000 -nets VDD -layer 25 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1.8000 -nets VDD -layer 27 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 127.6000 -nets VDD -layer 27 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 128.1400 -nets VDD -layer 29 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1.8000 -nets VDD -layer 29 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 4.6000 -nets VSS -layer 23 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 124.8000 -nets VSS -layer 23 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 125.3400 -nets VSS -layer 25 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 4.6000 -nets VSS -layer 25 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 4.6000 -nets VSS -layer 27 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 124.8000 -nets VSS -layer 27 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 125.3400 -nets VSS -layer 29 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 4.6000 -nets VSS -layer 29 -width 2.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal7 straps for net VDD
create_power_straps  -direction horizontal  -start_at 9.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 14.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 19.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 24.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 34.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 39.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 54.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 59.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 64.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 69.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 74.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 79.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 84.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 89.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 94.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 99.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 104.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 109.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 114.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 119.6850 -nets VDD  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal7 straps for net VSS
create_power_straps  -direction horizontal  -start_at 11.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 16.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 21.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 26.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 31.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 36.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 41.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 46.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 51.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 56.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 61.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 66.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 71.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 76.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 81.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 86.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 91.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 96.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 101.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 106.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 111.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 116.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 121.9150 -nets VSS  -layer 23 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VDD
create_power_straps  -direction vertical  -start_at 9.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 14.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 19.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 24.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 44.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 54.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 59.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 64.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 69.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 74.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 79.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 84.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 89.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 94.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 99.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 104.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 109.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 114.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 119.7500 -nets VDD  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal8 straps for net VSS
create_power_straps  -direction vertical  -start_at 11.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 16.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 21.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 26.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 31.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 36.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 41.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 46.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 51.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 56.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 61.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 66.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 71.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 76.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 81.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 86.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 91.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 96.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 101.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 106.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 111.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 116.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 121.8500 -nets VSS  -layer 25 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VDD
create_power_straps  -direction horizontal  -start_at 9.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 14.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 19.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 24.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 29.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 34.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 39.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 44.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 49.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 54.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 59.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 64.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 69.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 74.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 79.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 84.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 89.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 94.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 99.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 104.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 109.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 114.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 119.5500 -nets VDD  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 129.1400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal9 straps for net VSS
create_power_straps  -direction horizontal  -start_at 12.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 17.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 22.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 27.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 32.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 37.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 42.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 47.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 52.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 57.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 62.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 67.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 72.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 77.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 82.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 87.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 92.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 97.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 102.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 107.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 112.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 117.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 122.0500 -nets VSS  -layer 27 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 126.3400 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal10 straps for net VDD
create_power_straps  -direction vertical  -start_at 9.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 14.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 19.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 24.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 29.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 34.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 39.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 44.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 49.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 54.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 59.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 64.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 69.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 74.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 79.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 84.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 89.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 94.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 99.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 104.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 109.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 114.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 119.5500 -nets VDD  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 0.8000 -start_high_ends coordinate  -start_high_ends_coordinate 128.6000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal10 straps for net VSS
create_power_straps  -direction vertical  -start_at 12.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 17.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 22.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 27.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 32.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 37.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 42.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 47.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 52.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 57.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 62.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 67.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 72.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 77.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 82.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 87.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 92.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 97.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 102.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 107.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 112.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 117.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 122.0500 -nets VSS  -layer 29 -width 1.7000 -pitch_within_group 5.0000 -start_low_ends coordinate  -start_low_ends_coordinate 3.6000 -start_high_ends coordinate  -start_high_ends_coordinate 125.8000 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
